-- Fase 4 / Migration 12: relazioni familiari, eta e audit.
-- Solo DB locale in questa slice; le API/UI verranno allineate nelle slice successive.

begin;

create table if not exists public.profile_age_overrides (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null
    references public.profiles (id) on delete restrict,
  treat_as_minor boolean not null,
  reason text not null
    constraint profile_age_overrides_reason_check
    check (char_length(btrim(reason)) >= 10),
  overridden_by_auth_user_id uuid
    references auth.users (id) on delete set null,
  overridden_at timestamptz not null default now(),
  active boolean not null default true,
  revoked_by_auth_user_id uuid
    references auth.users (id) on delete set null,
  revoked_at timestamptz,
  revocation_reason text,
  constraint profile_age_overrides_revocation_check
    check (
      (active and revoked_at is null and revoked_by_auth_user_id is null)
      or (not active and revoked_at is not null)
    )
);

create unique index if not exists profile_age_overrides_active_profile_idx
  on public.profile_age_overrides (profile_id)
  where active = true;

create index if not exists profile_age_overrides_profile_idx
  on public.profile_age_overrides (profile_id, overridden_at desc);

create table if not exists public.profile_relationship_audit (
  id bigint generated by default as identity primary key,
  relationship_id uuid,
  source_profile_id uuid,
  target_profile_id uuid,
  action text not null
    constraint profile_relationship_audit_action_check
    check (action in ('created', 'modified', 'revoked', 'deleted')),
  performed_by_auth_user_id uuid,
  actor_profile_id uuid,
  actor_name_snapshot text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists profile_relationship_audit_relationship_idx
  on public.profile_relationship_audit (relationship_id, created_at desc);

create index if not exists profile_relationship_audit_target_idx
  on public.profile_relationship_audit (target_profile_id, created_at desc);

create index if not exists profile_relationship_audit_actor_idx
  on public.profile_relationship_audit (performed_by_auth_user_id, created_at desc);

alter table public.profile_age_overrides enable row level security;
alter table public.profile_relationship_audit enable row level security;

revoke all on table public.profile_age_overrides from anon, authenticated;
revoke all on table public.profile_relationship_audit from anon, authenticated;
grant select, insert, update on table public.profile_age_overrides to authenticated;
grant all on table public.profile_age_overrides to service_role;
grant all on table public.profile_relationship_audit to service_role;

alter table public.profile_age_overrides
  alter column overridden_by_auth_user_id drop not null;

drop policy if exists profile_age_overrides_admin_select on public.profile_age_overrides;
create policy profile_age_overrides_admin_select
  on public.profile_age_overrides for select to authenticated
  using ((select private.has_account_role('admin')));

drop policy if exists profile_age_overrides_admin_insert on public.profile_age_overrides;
create policy profile_age_overrides_admin_insert
  on public.profile_age_overrides for insert to authenticated
  with check (
    (select private.has_account_role('admin'))
    and overridden_by_auth_user_id = (select auth.uid())
    and char_length(btrim(reason)) >= 10
  );

drop policy if exists profile_age_overrides_admin_update on public.profile_age_overrides;
create policy profile_age_overrides_admin_update
  on public.profile_age_overrides for update to authenticated
  using ((select private.has_account_role('admin')))
  with check ((select private.has_account_role('admin')));

create or replace function private.is_profile_minor(
  p_profile_id uuid,
  p_at_date date default current_date
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $$
  select coalesce(
    (
      select pao.treat_as_minor
      from public.profile_age_overrides pao
      where pao.profile_id = p_profile_id
        and pao.active
      order by pao.overridden_at desc
      limit 1
    ),
    (
      select case
        when p.birth_date is null then true
        else p_at_date < (p.birth_date + interval '18 years')::date
      end
      from public.profiles p
      where p.id = p_profile_id
    ),
    true
  )
$$;

create or replace function private.has_active_relationship_permission(
  p_target_profile_id uuid,
  p_permission text
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $$
  select exists (
    select 1
    from public.profile_relationships pr
    where pr.source_profile_id = (select private.current_profile_id())
      and pr.target_profile_id = p_target_profile_id
      and pr.status = 'active'
      and pr.valid_from <= current_date
      and (pr.valid_until is null or pr.valid_until >= current_date)
      and case p_permission
        when 'view_schedule' then pr.can_view_schedule
        when 'confirm_attendance' then pr.can_confirm_attendance
        when 'view_payments' then pr.can_view_payments
        when 'view_medical_status' then pr.can_view_medical_status
        when 'view_documents' then pr.can_view_documents
        when 'sign_documents' then pr.can_sign_documents
        when 'receive_messages' then pr.can_receive_messages
        else false
      end
      and (
        (
          (select private.is_profile_minor(p_target_profile_id))
          and pr.relationship_type in ('parent', 'guardian', 'caregiver', 'delegate')
        )
        or (
          not (select private.is_profile_minor(p_target_profile_id))
          and pr.relationship_type = 'delegate'
          and pr.verified_at is not null
        )
      )
  )
$$;

create or replace function private.can_view_related_schedule(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'view_schedule') $$;

create or replace function private.can_confirm_related_attendance(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'confirm_attendance') $$;

create or replace function private.can_view_related_payments(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'view_payments') $$;

create or replace function private.can_view_related_medical_status(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'view_medical_status') $$;

create or replace function private.can_view_related_documents(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'view_documents') $$;

create or replace function private.can_sign_related_documents(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'sign_documents') $$;

create or replace function private.can_receive_related_messages(p_target_profile_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, private
as $$ select private.has_active_relationship_permission(p_target_profile_id, 'receive_messages') $$;

revoke all on all functions in schema private from public, anon, authenticated;
grant execute on function private.is_profile_minor(uuid, date) to authenticated, service_role;
grant execute on function private.has_active_relationship_permission(uuid, text) to authenticated, service_role;
grant execute on function private.can_view_related_schedule(uuid) to authenticated, service_role;
grant execute on function private.can_confirm_related_attendance(uuid) to authenticated, service_role;
grant execute on function private.can_view_related_payments(uuid) to authenticated, service_role;
grant execute on function private.can_view_related_medical_status(uuid) to authenticated, service_role;
grant execute on function private.can_view_related_documents(uuid) to authenticated, service_role;
grant execute on function private.can_sign_related_documents(uuid) to authenticated, service_role;
grant execute on function private.can_receive_related_messages(uuid) to authenticated, service_role;

create or replace function private.audit_profile_relationship_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth, private
as $$
declare
  v_actor_auth_user_id uuid := auth.uid();
  v_actor_profile_id uuid;
  v_actor_name text;
  v_action text;
  v_relationship_id uuid;
  v_source_profile_id uuid;
  v_target_profile_id uuid;
  v_details jsonb;
begin
  select aa.owner_profile_id, concat_ws(' ', p.first_name, p.last_name)
    into v_actor_profile_id, v_actor_name
  from public.app_accounts aa
  join public.profiles p on p.id = aa.owner_profile_id
  where aa.auth_user_id = v_actor_auth_user_id
  limit 1;

  if tg_op = 'INSERT' then
    v_action := 'created';
    v_relationship_id := new.id;
    v_source_profile_id := new.source_profile_id;
    v_target_profile_id := new.target_profile_id;
    v_details := jsonb_build_object('new', to_jsonb(new));
  elsif tg_op = 'UPDATE' then
    v_action := case
      when old.status <> 'revoked' and new.status = 'revoked' then 'revoked'
      else 'modified'
    end;
    v_relationship_id := new.id;
    v_source_profile_id := new.source_profile_id;
    v_target_profile_id := new.target_profile_id;
    v_details := jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new));
  else
    v_action := 'deleted';
    v_relationship_id := old.id;
    v_source_profile_id := old.source_profile_id;
    v_target_profile_id := old.target_profile_id;
    v_details := jsonb_build_object('old', to_jsonb(old));
  end if;

  insert into public.profile_relationship_audit (
    relationship_id,
    source_profile_id,
    target_profile_id,
    action,
    performed_by_auth_user_id,
    actor_profile_id,
    actor_name_snapshot,
    details
  ) values (
    v_relationship_id,
    v_source_profile_id,
    v_target_profile_id,
    v_action,
    v_actor_auth_user_id,
    v_actor_profile_id,
    nullif(v_actor_name, ''),
    v_details
  );

  return coalesce(new, old);
end;
$$;

create or replace function private.prevent_profile_relationship_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth, private
as $$
begin
  raise exception 'profile_relationship_audit is append-only';
end;
$$;

drop trigger if exists profile_relationship_audit_immutable on public.profile_relationship_audit;
create trigger profile_relationship_audit_immutable
  before update or delete on public.profile_relationship_audit
  for each row execute function private.prevent_profile_relationship_audit_mutation();

drop trigger if exists profile_relationships_audit on public.profile_relationships;
create trigger profile_relationships_audit
  after insert or update or delete on public.profile_relationships
  for each row execute function private.audit_profile_relationship_change();

revoke delete on table public.profile_relationships from authenticated;
drop policy if exists profile_relationships_admin_delete on public.profile_relationships;

revoke all on function private.audit_profile_relationship_change() from public, anon, authenticated;
revoke all on function private.prevent_profile_relationship_audit_mutation() from public, anon, authenticated;

comment on table public.profile_age_overrides is
  'Override amministrativi motivati della maggiore/minore eta; le righe revocate restano come storico.';
comment on table public.profile_relationship_audit is
  'Audit append-only di creazione, modifica, revoca e cancellazione delle relazioni familiari.';
comment on function private.is_profile_minor(uuid, date) is
  'Calcola la minore eta con override amministrativo; dati mancanti negano l accesso familiare operativo.';

commit;
